name = "maison-recipes"
main = "worker/index.ts"
compatibility_date = "2026-10-09"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "maison-recipes"
database_id = "03c804b3-76eb-496d-8f03-2c9da06211aa"
migrations_dir = "migrations"

[vars]
ACCESS_AUD = "f11011350a051072ad5a154cf7d0698c21cf822b2d73a4bb5248e904a4af17c8"
ACCESS_TEAM_DOMAIN = "xjdevs.cloudflareaccess.com"
ALLOWED_EMAIL = "dmdani1997@gmail.com"
